trigger: 
 - master

pool:
  vmImage: ubuntu-latest

jobs:
- job: RunCheckov
  displayName: 'Run Checkov'
  steps:
    - checkout: self
    - task: Bash@3
      displayName: 'Run Checkov Test'
      inputs:
        targetType: 'inline'
        failOnStderr: false
        script: |
          cd $(System.DefaultWorkingDirectory)
          pwd
          ls
          docker pull bridgecrew/checkov
          docker run \
          --volume $(System.DefaultWorkingDirectory):/tf bridgecrew/checkov \
          --directory /tf \
          --output junitxml \
          --soft-fail > $(System.DefaultWorkingDirectory)/Checkov-Report.xml
    - task: PublishTestResults@2
      inputs:
        testRunTitle: "Checkov Results"
        failTaskOnFailedTests: true
        testResultsFormat: "JUnit"
        testResultsFiles: "CheckovReport.xml"
        searchFolder: "$(System.DefaultWorkingDirectory)"
      displayName: "Publish Checkov scan results"

# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
#trigger:
#- master

#resources:
#- repo: self

#variables:
#  tag: '$(Build.BuildId)'

#stages:
#- stage: QualityCheckStage
#  displayName: Quality Check Stage
#  jobs:
#  - job: QualityCheck
#    displayName: Run Checkov
#    steps:
#    - script: |
#      echo Connell Test
#       pwd
#- stage: Build
#  displayName: Build image
#  jobs:
#  - job: Build
#    displayName: Build
#    pool:
#      vmImage: ubuntu-latest
#    steps:
#    - task: Docker@2
#      displayName: Build an image
#      inputs:
#        command: build
#        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
#        tags: |
#          $(tag)
