# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: QualityCheckStage
  displayName: Quality Check Stage
  jobs:
  - job: QualityCheck
    displayName: Run Checkov
    steps:
    - script: |
      docker run -t -v $(System.DefaultWorkingDirectory):/tf bridgecrew/checkov --directory .
    displayName: 'Checkov Static Code Analysis'
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
