trigger: 
 - master

pool:
  vmImage: ubuntu-latest

jobs:
- job: RunCheckov
  displayName: 'Run Checkov'
  steps:
    - checkout: self
    - task: Bash@3
      displayName: 'Run Checkov Test'
      inputs:
        targetType: 'inline'
        failOnStderr: false
        script: |
          cd $(System.DefaultWorkingDirectory)
          pwd
          mkdir Reports
          docker pull bridgecrew/checkov
          docker run \
          --volume $(pwd):/tf bridgecrew/checkov \
          --directory /tf \
          --skip-check CKV_DOCKER* \
          --output junitxml \
          --soft-fail > $(pwd)/Reports/Checkov-Report.xml
    - task: PublishTestResults@2
      displayName: 'Publish Checkov scan results'
      inputs:
        testRunTitle: "Checkov Results"
        failTaskOnFailedTests: true
        testResultsFormat: "JUnit"
        testResultsFiles: "Checkov-Report.xml"
        searchFolder: "$(System.DefaultWorkingDirectory)"
    - task: Bash@3
      displayName: 'Run AppThreat SAST-Scan'
      inputs:
        targetType: 'inline'
        failOnStderr: false
        script: |
          cd $(System.DefaultWorkingDirectory)
          pwd
          docker run --rm -e "WORKSPACE=${PWD}" \
          -v "$PWD:/app:cached" quay.io/appthreat/sast-scan scan \
          --src /app \
          --type nodejs --out_dir ${pwd}/Reports
    - task: PublishBuildArtifacts@1
      inputs:
       pathToPublish: '$(pwd)/Reports'
       artifactName: Checkov-Report.xml
    - task: PublishBuildArtifacts@1
      inputs:
       pathToPublish: '$(pwd)/Reports'
       artifactName: '*.json'
    - task: Docker@2
      displayName: 'Build Docker Image'
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
